### ISSUE TITLE
Creación nómina

### ISSUE THREAD

**Issue by Hallowed26** [odoo-chile/l10n_cl_hr_payroll#1]
Buenas tardes,

He instalado la aplicación de payroll para Chile, la he visto bien completa, sin embargo al momento de crear la nómina me aparece el siguiente error. 

![integrity error](https://cloud.githubusercontent.com/assets/17860472/13792344/2b0e5e16-ead0-11e5-9946-c2bbc431b26a.jpg)

He intentado revisando las autorizaciones del usuario, desinstalando e instalando nuevamente y no he tenido éxito.

Les agradezco por su ayuda!!!

**Comment by nelsonramirezs** [comment]
Hola, Intenta realizar la nómina a través de procesamiento de nóminas.
Haz clic en Crear, colocas el nombre, período, Indicadores y haz clic en
Generar, añadir trabajadores, Generar.

Saludos,

2016-03-15 16:06 GMT-04:00 Hallowed26 notifications@github.com:

> Buenas tardes,
> 
> He instalado la aplicación de payroll para Chile, la he visto bien
> completa, sin embargo al momento de crear la nómina me aparece el siguiente
> error.
> 
> [image: integrity error]
> https://cloud.githubusercontent.com/assets/17860472/13792344/2b0e5e16-ead0-11e5-9946-c2bbc431b26a.jpg
> 
> He intentado revisando las autorizaciones del usuario, desinstalando e
> instalando nuevamente y no he tenido éxito.
> 
> Les agradezco por su ayuda!!!
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/odoo-chile/l10n_cl_hr_payroll/issues/1

## 

Ing. Nelson Ramírez
M +56 9 42514111

**Comment by Danisan** [comment]
El procesamiento de nóminas resuelve el problema, por lo que cierro este issue.

**Comment by Hallowed26** [comment]
Muchas gracias!!!
